ci:
  skip: [
    manifest,
    perltidy,
  ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: local
    hooks:
      - id: manifest
        name: update MANIFEST
        entry: perl Makefile.PL && make manifest
        language: system
      - id: perltidy
        name: perltidy
        description: Run the perltidy source code formatter on Perl source files
        entry: perltidy
        args: [
          --backup-and-modify-in-place,
          --backup-file-extension=/,
        ]
        language: perl
        types: [perl]

# vim:set ft=yaml ts=2 sw=2 et:
